PainelDLX\Domain\GruposUsuarios\Entities\GrupoUsuario:
    type: entity
    table: dlx_grupos_usuarios
    repositoryClass: PainelDLX\Infra\ORM\Doctrine\Repositories\GrupoUsuarioRepository
    id:
        grupo_usuario_id:
            type: integer
            id: true
            nullable: false
            generator:
                strategy: auto
    fields:
        alias:
            type: string
            length: 50
            nullable: false
        nome:
            type: string
            length: 100
            nullable: false
        deletado:
            type: integer
    manyToMany:
        usuarios:
            targetEntity: PainelDLX\Domain\Usuarios\Entities\Usuario
            mappedBy: grupos
        permissoes:
            targetEntity: PainelDLX\Domain\PermissoesUsuario\Entities\PermissaoUsuario
            inversedBy: grupos
            fetch: EAGER
            cascade:
                - persist
                - merge
            joinTable:
                name: dlx_permissoes_x_grupos
                joinColumns:
                    grupo_usuario_id:
                        referencedColumnName: grupo_usuario_id
                inverseJoinColumns:
                    permissao_usuario_id:
                        referencedColumnName: permissao_usuario_id
