PainelDLX\Domain\Modulos\Entities\Menu:
    type: entity
    table: dlx_config_smtp
    repositoryClass: PainelDLX\Infra\ORM\Doctrine\Repositories\MenuRepository
    id:
        menu_item_id:
            type: integer
            id: true
            nullable: false
            generator:
                strategy: auto
    fields:
        nome:
            type: string
            nullable: false
            length: 50
        link:
            type: string
            nullable: false
            length: 50
    manyToOne:
        menu:
            targetEntity: Menu
            inversedBy: itens
            joinColumns:
                idMenu:
                    referencedColumnName: idMenu