PainelDLX\Domain\Usuarios\Entities\ResetSenha:
    type: entity
    table: dlx_reset_senha
    repositoryClass: PainelDLX\Infra\ORM\Doctrine\Repositories\ResetSenhaRepository
    id:
        reset_senha_id:
            type: integer
            id: true
            generator:
                strategy: auto
    fields:
        data:
            type: datetime
            nullable: false
        hash:
            type: string
            nullable: false
            length: 50
        utilizado:
            type: boolean
            nullable: false
    manyToOne:
        usuario:
            targetEntity: Usuario
            joinColumns:
                usuario_id:
                    referencedColumnName: usuario_id