PainelDLX\Domain\Modulos\Entities\MenuItem:
    type: entity
    table: dlx.MenuItem
    repositoryClass: PainelDLX\Infrastructure\ORM\Doctrine\Repositories\MenuItemRepository
    id:
        id:
            type: integer
            id: true
            nullable: false
            generator:
                strategy: auto
            column: menu_item_id
    fields:
        nome:
            type: string
            nullable: false
            length: 50
        link:
            type: string
            nullable: false
            length: 50
        deletado:
            type: boolean
            nullable: false
            options:
                default: false
    manyToOne:
        menu:
            targetEntity: Menu
            inversedBy: itens
            joinColumns:
                menu_id:
                    referencedColumnName: menu_id
    manyToMany:
        permissoes:
            targetEntity: PainelDLX\Domain\PermissoesUsuario\Entities\PermissaoUsuario
            joinTable:
                name: dlx.MenuItem_x_PermissaoUsuario
                joinColumns:
                    menu_item_id:
                        referencedColumnName: menu_item_id
                inverseJoinColumns:
                    permissao_usuario_id:
                        referencedColumnName: permissao_usuario_id