PainelDLX\Domain\Modulos\Entities\Menu:
    type: entity
    table: dlx.Menu
    repositoryClass: PainelDLX\Infrastructure\ORM\Doctrine\Repositories\MenuRepository
    id:
        id:
            type: integer
            id: true
            nullable: false
            generator:
                strategy: auto
            column: menu_id
    fields:
        nome:
            type: string
            nullable: false
            length: 50
        deletado:
            type: boolean
            nullable: false
            options:
                default: false
    oneToMany:
        itens:
            targetEntity: MenuItem
            mappedBy: menu
            joinColumns:
                menu_id:
                    referencedColumnName: menu_id