PainelDLX\Domain\GruposUsuarios\Entities\GrupoUsuario:
    type: entity
    table: dlx.GrupoUsuario
    repositoryClass: PainelDLX\Infrastructure\ORM\Doctrine\Repositories\GrupoUsuarioRepository
    id:
        id:
            type: integer
            id: true
            nullable: false
            generator:
                strategy: auto
            column: grupo_usuario_id
    fields:
        alias:
            type: string
            length: 50
            nullable: false
        nome:
            type: string
            length: 100
            nullable: false
        deletado:
            type: integer
    manyToMany:
        usuarios:
            targetEntity: PainelDLX\Domain\Usuarios\Entities\Usuario
            mappedBy: grupos
        permissoes:
            targetEntity: PainelDLX\Domain\PermissoesUsuario\Entities\PermissaoUsuario
            inversedBy: grupos
            fetch: EAGER
            cascade:
                - persist
                - merge
            joinTable:
                name: dlx.PermissaoUsuario_x_GrupoUsuario
                joinColumns:
                    grupo_usuario_id:
                        referencedColumnName: grupo_usuario_id
                inverseJoinColumns:
                    permissao_usuario_id:
                        referencedColumnName: permissao_usuario_id
